use std::collections::HashSet;
use std::io;
use std::path::{Path, PathBuf};
use std::process;

use mdbook_preprocessor::book::{Book, BookItem, Chapter, SectionNumber};
use mdbook_preprocessor::errors::Result;
use mdbook_preprocessor::{parse_input, Preprocessor, PreprocessorContext};
use regex::Regex;

const EXCALIDRAW_TEMPLATE: &str = include_str!("assets/excalidraw-page.html");
const TOC_PLACEHOLDER: &str = "<!-- mdbook-obsidian toc -->";

// ---------------------------------------------------------------------------
// Preprocessor entry point
// ---------------------------------------------------------------------------

struct ObsidianPreprocessor;

impl Preprocessor for ObsidianPreprocessor {
    fn name(&self) -> &str {
        "obsidian"
    }

    fn run(&self, ctx: &PreprocessorContext, mut book: Book) -> Result<Book> {
        let verbose = ctx
            .config
            .get::<bool>("preprocessor.obsidian.verbose")
            .unwrap_or(None)
            .unwrap_or(false);

        // --- Pass 0: TOC generation --------------------------------------
        run_toc_pass(ctx, &mut book, verbose);

        // --- Pass 1: anchor normalization --------------------------------
        // Capture optional leading `!` so we can skip image links.
        let link_re = Regex::new(r"(!?)\[([^\]]*)\]\(([^)]+)\)").expect("valid regex");
        book.for_each_mut(|item| {
            if let BookItem::Chapter(chapter) = item {
                chapter.content = process_content(&link_re, &chapter.content, verbose);
            }
        });

        // --- Pass 2: Excalidraw link detection and rewrite ---------------
        // Matches [text](path.excalidraw) and [text](path.excalidraw.md).
        // The .md variant appears when the Obsidian Excalidraw plugin stores drawings as
        // .excalidraw.md files; mdBook then converts .md → .html, producing broken links.
        let excalidraw_link_re =
            Regex::new(r"(!?)\[([^\]]*)\]\(([^)]*\.excalidraw(?:\.md)?)\)").expect("valid regex");
        // Matches [[path.excalidraw]] and ![[path.excalidraw]] and [[path.excalidraw|alias]]
        let excalidraw_wiki_re =
            Regex::new(r"(!?)\[\[([^\]]+\.excalidraw)(?:\|([^\]]*))?\]\]").expect("valid regex");

        let src_dir = ctx.root.join(&ctx.config.book.src);
        let mut all_refs: Vec<ExcalidrawRef> = Vec::new();
        // Slugs of chapters that ARE excalidraw files (listed directly in SUMMARY.md).
        // We convert them in-place; the injection loop must skip their slugs to avoid
        // creating a duplicate chapter.
        let mut summary_slugs: HashSet<String> = HashSet::new();

        book.for_each_mut(|item| {
            if let BookItem::Chapter(chapter) = item {
                // Does this chapter's source file IS an excalidraw drawing?
                let is_excalidraw_source = chapter
                    .source_path
                    .as_ref()
                    .and_then(|p| p.to_str())
                    .map(|s| s.ends_with(".excalidraw.md") || s.ends_with(".excalidraw"))
                    .unwrap_or(false);

                if is_excalidraw_source {
                    // Chapter is a drawing listed directly in SUMMARY.md.
                    // Convert it in-place to the viewer page.
                    let source = chapter.source_path.as_ref().unwrap();
                    let file_path = src_dir.join(source);

                    // Strip double extension: "Name.excalidraw.md" → stem "Name.excalidraw" → "Name"
                    let stem_raw = source
                        .file_stem()
                        .and_then(|s| s.to_str())
                        .unwrap_or("drawing");
                    let name = stem_raw.strip_suffix(".excalidraw").unwrap_or(stem_raw).to_string();
                    let slug = excalidraw_slug(&name);

                    let r = ExcalidrawRef { file_path: file_path.clone(), slug: slug.clone(), name };

                    chapter.content = match read_excalidraw_json(&file_path) {
                        Ok(json) => make_excalidraw_chapter(&r, &json).content,
                        Err(msg) => {
                            if verbose {
                                eprintln!("[mdbook-obsidian] {}: {msg}", file_path.display());
                            }
                            make_excalidraw_error_chapter(&r, &msg).content
                        }
                    };
                    // Move this chapter's output path into the canonical _excalidraw/ slot
                    // so that links generated by pass 2 from other chapters resolve correctly.
                    chapter.path = Some(PathBuf::from(format!("_excalidraw/{}.md", slug)));

                    summary_slugs.insert(slug);
                } else {
                    // Normal chapter: scan for links that point to excalidraw files.
                    let chapter_dir = chapter
                        .source_path
                        .as_ref()
                        .and_then(|p| p.parent())
                        .map(|p| src_dir.join(p))
                        .unwrap_or_else(|| src_dir.clone());
                    let depth = chapter
                        .path
                        .as_ref()
                        .map(|p| p.components().count().saturating_sub(1))
                        .unwrap_or(0);

                    chapter.content = process_excalidraw(
                        &excalidraw_link_re,
                        &excalidraw_wiki_re,
                        &chapter.content,
                        &chapter_dir,
                        depth,
                        verbose,
                        &mut all_refs,
                    );
                }
            }
        });

        // Inject one synthetic chapter per unique excalidraw slug that was NOT
        // already handled in-place above (i.e. not in SUMMARY.md directly).
        let mut seen = summary_slugs;
        for r in &all_refs {
            if !seen.insert(r.slug.clone()) {
                continue;
            }
            let chapter = match read_excalidraw_json(&r.file_path) {
                Ok(json) => make_excalidraw_chapter(r, &json),
                Err(msg) => {
                    if verbose {
                        eprintln!("[mdbook-obsidian] {}: {msg}", r.file_path.display());
                    }
                    make_excalidraw_error_chapter(r, &msg)
                }
            };
            book.items.push(BookItem::Chapter(chapter));
        }

        // --- Pass 3: hard line breaks ------------------------------------
        let hard_line_breaks = ctx
            .config
            .get::<bool>("preprocessor.obsidian.hard_line_breaks")
            .unwrap_or(None)
            .unwrap_or(false);

        if hard_line_breaks {
            book.for_each_mut(|item| {
                if let BookItem::Chapter(chapter) = item {
                    let path_str = chapter
                        .path
                        .as_ref()
                        .and_then(|p| p.to_str())
                        .unwrap_or("");
                    if path_str.is_empty() || path_str.starts_with("_excalidraw/") {
                        return;
                    }
                    chapter.content = patch_hard_line_breaks(&chapter.content);
                }
            });
        }

        // --- Pass 4: heading insertion -----------------------------------
        let insert_heading = ctx
            .config
            .get::<bool>("preprocessor.obsidian.insert_heading")
            .unwrap_or(None)
            .unwrap_or(false);

        if insert_heading {
            book.for_each_mut(|item| {
                if let BookItem::Chapter(chapter) = item {
                    // Skip draft chapters (no output path) and excalidraw viewers.
                    let path_str = chapter
                        .path
                        .as_ref()
                        .and_then(|p| p.to_str())
                        .unwrap_or("");
                    if path_str.is_empty() || path_str.starts_with("_excalidraw/") {
                        return;
                    }
                    let first = chapter.content.lines().find(|l| !l.trim().is_empty());
                    if first.map(|l| l.starts_with("# ")).unwrap_or(false) {
                        return;
                    }
                    let heading = format!("# {}\n\n", chapter.name);
                    chapter.content.insert_str(0, &heading);
                }
            });
        }

        Ok(book)
    }

    fn supports_renderer(&self, _renderer: &str) -> Result<bool> {
        Ok(true)
    }
}

// ---------------------------------------------------------------------------
// TOC generation (Pass 0)
// ---------------------------------------------------------------------------

fn run_toc_pass(ctx: &PreprocessorContext, book: &mut Book, verbose: bool) {
    let generate_toc = ctx
        .config
        .get::<bool>("preprocessor.obsidian.generate_toc")
        .unwrap_or(None)
        .unwrap_or(false);
    if !generate_toc {
        return;
    }

    let custom_ignore = ctx
        .config
        .get::<String>("preprocessor.obsidian.toc_ignore_file")
        .unwrap_or(None);

    let src_dir = ctx.root.join(&ctx.config.book.src);
    let summary_content =
        std::fs::read_to_string(src_dir.join("SUMMARY.md")).unwrap_or_default();

    let covered = toc_covered_paths(&book.items);
    let files = toc_scan_files(&src_dir, &covered, custom_ignore.as_deref(), verbose);

    if files.is_empty() {
        if verbose {
            eprintln!("[mdbook-obsidian] toc: no uncovered files found");
        }
        return;
    }

    // Continue section numbering after existing top-level numbered chapters.
    let start_num = book
        .items
        .iter()
        .filter_map(|item| {
            if let BookItem::Chapter(ch) = item {
                ch.number.as_ref().and_then(|n| n.first().copied())
            } else {
                None
            }
        })
        .max()
        .unwrap_or(0)
        + 1;

    let new_items = toc_build_items(&files, &src_dir, Path::new(""), &[], &[], start_num);
    if new_items.is_empty() {
        return;
    }

    let toc_markdown = toc_render_markdown(&new_items, 0);

    let insert_at =
        toc_placeholder_index(&summary_content, &book.items).unwrap_or(book.items.len());

    if verbose {
        eprintln!(
            "[mdbook-obsidian] toc: inserting {} top-level item(s) at position {insert_at}",
            new_items.len()
        );
    }

    for (i, item) in new_items.into_iter().enumerate() {
        book.items.insert(insert_at + i, item);
    }

    // Replace the placeholder in all chapter content (existing + newly inserted).
    book.for_each_mut(|item| {
        if let BookItem::Chapter(ch) = item {
            if ch.content.contains(TOC_PLACEHOLDER) {
                ch.content = ch.content.replace(TOC_PLACEHOLDER, &toc_markdown);
            }
        }
    });
}

/// Collect source_paths of all chapters already in the book (recursive).
fn toc_covered_paths(items: &[BookItem]) -> HashSet<PathBuf> {
    let mut covered = HashSet::new();
    for item in items {
        if let BookItem::Chapter(ch) = item {
            if let Some(sp) = &ch.source_path {
                covered.insert(sp.clone());
            }
            covered.extend(toc_covered_paths(&ch.sub_items));
        }
    }
    covered
}

/// Walk `src_dir` respecting `.gitignore` (and optional extra ignore file).
/// Returns uncovered `.md` files sorted by relative path.
fn toc_scan_files(
    src_dir: &Path,
    covered: &HashSet<PathBuf>,
    custom_ignore: Option<&str>,
    verbose: bool,
) -> Vec<PathBuf> {
    let mut builder = ignore::WalkBuilder::new(src_dir);
    builder.standard_filters(true);
    if let Some(f) = custom_ignore {
        builder.add_custom_ignore_filename(f);
    }

    let mut files = Vec::new();
    for result in builder.build() {
        let entry = match result {
            Ok(e) => e,
            Err(err) => {
                if verbose {
                    eprintln!("[mdbook-obsidian] toc walk error: {err}");
                }
                continue;
            }
        };
        let path = entry.path();
        if !path.is_file() {
            continue;
        }
        if path.extension().and_then(|e| e.to_str()) != Some("md") {
            continue;
        }
        let rel = match path.strip_prefix(src_dir) {
            Ok(r) => r.to_path_buf(),
            Err(_) => continue,
        };
        let name = rel.file_name().and_then(|n| n.to_str()).unwrap_or("");
        if name == "SUMMARY.md" {
            continue;
        }
        if !covered.contains(&rel) {
            files.push(rel);
        }
    }
    files.sort();
    files
}

/// Recursively build `BookItem`s from a sorted list of relative file paths.
/// Directories with an `index.md` / `README.md` become clickable section headers;
/// otherwise they become draft (non-clickable) headers.
///
/// `number_prefix` is the section-number ancestry (e.g. `[3]` means we're inside
/// the third top-level group).  `start_idx` is the 1-based index for the first
/// item at the current depth; siblings increment it sequentially.
fn toc_build_items(
    files: &[PathBuf],
    src_dir: &Path,
    prefix: &Path,
    parent_names: &[String],
    number_prefix: &[u32],
    start_idx: u32,
) -> Vec<BookItem> {
    use std::collections::BTreeMap;

    let mut direct: Vec<&PathBuf> = Vec::new();
    let mut subdirs: BTreeMap<String, Vec<&PathBuf>> = BTreeMap::new();

    for file in files {
        let Ok(rel) = file.strip_prefix(prefix) else {
            continue;
        };
        let mut comps = rel.components();
        match (comps.next(), comps.next()) {
            (Some(_), None) => direct.push(file),
            (Some(first), Some(_)) => {
                let dir = first.as_os_str().to_string_lossy().into_owned();
                subdirs.entry(dir).or_default().push(file);
            }
            _ => {}
        }
    }

    let mut items: Vec<BookItem> = Vec::new();
    let mut counter = start_idx;

    // Direct files (already sorted from scan).
    for rel_path in direct {
        let content = std::fs::read_to_string(src_dir.join(rel_path)).unwrap_or_default();
        let raw_stem = rel_path
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or("Untitled");
        // Strip the inner .excalidraw extension for files like "Drawing.excalidraw.md".
        let name = raw_stem.strip_suffix(".excalidraw").unwrap_or(raw_stem).to_string();
        let mut num = number_prefix.to_vec();
        num.push(counter);
        counter += 1;
        items.push(BookItem::Chapter(Chapter {
            name,
            content,
            number: Some(SectionNumber::new(num)),
            sub_items: vec![],
            path: Some(rel_path.clone()),
            source_path: Some(rel_path.clone()),
            parent_names: parent_names.to_vec(),
        }));
    }

    // Subdirectories (BTreeMap keeps them sorted).
    for (dir_name, dir_files) in subdirs {
        let subdir = prefix.join(&dir_name);
        let display = dir_name.replace(['-', '_'], " ");

        let mut child_parents = parent_names.to_vec();
        child_parents.push(display.clone());

        // index.md or README.md becomes the section's own page.
        let index_rel = subdir.join("index.md");
        let readme_rel = subdir.join("README.md");
        let (section_content, section_path, section_source) =
            if src_dir.join(&index_rel).exists() {
                let c = std::fs::read_to_string(src_dir.join(&index_rel)).unwrap_or_default();
                (c, Some(index_rel.clone()), Some(index_rel.clone()))
            } else if src_dir.join(&readme_rel).exists() {
                let c = std::fs::read_to_string(src_dir.join(&readme_rel)).unwrap_or_default();
                (c, Some(readme_rel.clone()), Some(readme_rel.clone()))
            } else {
                (String::new(), None, None)
            };

        let children: Vec<PathBuf> = dir_files
            .iter()
            .filter(|f| **f != &index_rel && **f != &readme_rel)
            .map(|f| (*f).clone())
            .collect();

        let mut my_num = number_prefix.to_vec();
        my_num.push(counter);
        counter += 1;

        let sub_items =
            toc_build_items(&children, src_dir, &subdir, &child_parents, &my_num, 1);

        if sub_items.is_empty() && section_path.is_none() {
            continue; // empty draft directory — skip
        }

        items.push(BookItem::Chapter(Chapter {
            name: display,
            content: section_content,
            number: Some(SectionNumber::new(my_num)),
            sub_items,
            path: section_path,
            source_path: section_source,
            parent_names: parent_names.to_vec(),
        }));
    }

    items
}

/// Find where to insert new chapters in `book.items` by locating the placeholder
/// in `SUMMARY.md` and counting which existing chapters precede it.
fn toc_placeholder_index(summary_content: &str, items: &[BookItem]) -> Option<usize> {
    let placeholder_pos = summary_content.find(TOC_PLACEHOLDER)?;
    let before = &summary_content[..placeholder_pos];

    let link_re = Regex::new(r"\]\(([^)]+\.md)\)").expect("valid regex");
    let paths_before: HashSet<PathBuf> = link_re
        .captures_iter(before)
        .map(|c| PathBuf::from(urlencoding::decode(c[1].trim()).unwrap_or_default().as_ref()))
        .collect();

    // Last top-level item whose source_path was listed before the placeholder.
    let last_idx = items.iter().rposition(|item| {
        if let BookItem::Chapter(ch) = item {
            if let Some(sp) = &ch.source_path {
                return paths_before.contains(sp);
            }
        }
        false
    });

    Some(last_idx.map(|i| i + 1).unwrap_or(0))
}

/// Render generated chapters as a nested markdown list (for in-chapter placeholder replacement).
fn toc_render_markdown(items: &[BookItem], depth: usize) -> String {
    let indent = "  ".repeat(depth);
    let mut out = String::new();
    for item in items {
        if let BookItem::Chapter(ch) = item {
            if let Some(path) = &ch.path {
                let path_str = path.to_string_lossy();
                // Excalidraw sources are redirected to _excalidraw/{slug}.html by Pass 2.
                // Compute that URL now rather than using the raw .excalidraw.md path,
                // which would be wrong and may contain spaces that break markdown links.
                let href = if path_str.ends_with(".excalidraw.md")
                    || path_str.ends_with(".excalidraw")
                {
                    format!("_excalidraw/{}.html", excalidraw_slug(&ch.name))
                } else {
                    path.with_extension("html")
                        .to_string_lossy()
                        .replace('\\', "/")
                };
                out.push_str(&format!("{}- [{}]({})\n", indent, ch.name, href));
            } else {
                out.push_str(&format!("{}- {}\n", indent, ch.name));
            }
            if !ch.sub_items.is_empty() {
                out.push_str(&toc_render_markdown(&ch.sub_items, depth + 1));
            }
        }
    }
    out
}

// ---------------------------------------------------------------------------
// Excalidraw reference
// ---------------------------------------------------------------------------

struct ExcalidrawRef {
    /// Absolute path to the .excalidraw file on disk.
    file_path: PathBuf,
    /// URL-safe slug used for `_excalidraw/{slug}.html`.
    slug: String,
    /// Human-readable display name (file stem, original casing).
    name: String,
}

fn excalidraw_slug(decoded_stem: &str) -> String {
    let slug: String = decoded_stem
        .to_lowercase()
        .replace(' ', "-")
        .chars()
        .filter(|c| c.is_alphanumeric() || *c == '-')
        .collect();
    slug.trim_matches('-').to_string()
}

/// Relative URL from a chapter at `depth` directory levels to the synthetic
/// excalidraw page for `slug`.
fn excalidraw_href(slug: &str, depth: usize) -> String {
    format!("{}_excalidraw/{}.html", "../".repeat(depth), slug)
}

/// Build a synthetic chapter that renders the Excalidraw scene.
fn make_excalidraw_chapter(r: &ExcalidrawRef, json: &str) -> Chapter {
    // Prevent </script> inside JSON from closing the surrounding script tag.
    let safe_json = json.replace("</", "<\\/");
    let html = EXCALIDRAW_TEMPLATE
        .replace("{{DRAWING_NAME}}", &r.name)
        .replace("{{SCENE_JSON}}", &safe_json);

    Chapter {
        name: r.name.clone(),
        content: html,
        number: None,
        sub_items: vec![],
        path: Some(PathBuf::from(format!("_excalidraw/{}.md", r.slug))),
        source_path: None,
        parent_names: vec![],
    }
}

/// Build a synthetic chapter that shows a human-readable error when the scene
/// data can't be extracted (e.g. compressed format not yet supported).
fn make_excalidraw_error_chapter(r: &ExcalidrawRef, error: &str) -> Chapter {
    let html = format!(
        "<div style=\"padding:2rem;border:2px solid #c00;border-radius:6px;\
         background:#fff5f5;color:#900;font-family:sans-serif\">\
         <h2>Cannot display: {name}</h2><p>{error}</p></div>",
        name = &r.name,
        error = error,
    );
    Chapter {
        name: r.name.clone(),
        content: html,
        number: None,
        sub_items: vec![],
        path: Some(PathBuf::from(format!("_excalidraw/{}.md", r.slug))),
        source_path: None,
        parent_names: vec![],
    }
}

/// Parse the `## Embedded Files` section of an `.excalidraw.md` file.
/// Returns pairs of `(fileId, vault-relative-path)`.
fn parse_embedded_files(content: &str) -> Vec<(String, String)> {
    let mut result = Vec::new();
    let section_start = match content.find("## Embedded Files") {
        Some(pos) => pos + "## Embedded Files".len(),
        None => return result,
    };
    // Section ends at the next `##` heading, `%%`, or EOF.
    let section_end = content[section_start..]
        .find("\n## ")
        .or_else(|| content[section_start..].find("\n%%"))
        .map(|p| section_start + p)
        .unwrap_or(content.len());

    for line in content[section_start..section_end].lines() {
        // Each line looks like: `<fileId>: [[path/to/file.png]]`
        if let Some((id, rest)) = line.split_once(": [[") {
            let id = id.trim().to_string();
            if !id.is_empty() {
                if let Some(path) = rest.strip_suffix("]]") {
                    result.push((id, path.to_string()));
                }
            }
        }
    }
    result
}

/// Inject embedded image files into the Excalidraw JSON's `files` object.
/// `file_path` is the path of the `.excalidraw.md` file; image paths in
/// `embedded` are resolved relative to its parent directory.
fn inject_embedded_files(
    json: &str,
    file_path: &Path,
    embedded: &[(String, String)],
) -> String {
    if embedded.is_empty() {
        return json.to_string();
    }
    let mut scene: serde_json::Value = match serde_json::from_str(json) {
        Ok(v) => v,
        Err(_) => return json.to_string(),
    };
    let dir = file_path.parent().unwrap_or(Path::new("."));
    let files_map = match scene.get_mut("files").and_then(|f| f.as_object_mut()) {
        Some(m) => m,
        None => return json.to_string(),
    };
    for (id, rel_path) in embedded {
        if files_map.contains_key(id) {
            continue; // already has inline data
        }
        let img_path = dir.join(rel_path);
        if let Ok(data) = std::fs::read(&img_path) {
            use base64::Engine as _;
            let b64 = base64::engine::general_purpose::STANDARD.encode(&data);
            let mime = match img_path.extension().and_then(|e| e.to_str()) {
                Some("jpg") | Some("jpeg") => "image/jpeg",
                Some("gif") => "image/gif",
                Some("svg") => "image/svg+xml",
                Some("webp") => "image/webp",
                _ => "image/png",
            };
            files_map.insert(
                id.clone(),
                serde_json::json!({
                    "mimeType": mime,
                    "id": id,
                    "dataURL": format!("data:{mime};base64,{b64}"),
                    "created": 0
                }),
            );
        }
    }
    serde_json::to_string(&scene).unwrap_or_else(|_| json.to_string())
}

/// Read the Excalidraw JSON from disk, returning `Err` with a human-readable
/// message when the file is missing, compressed, or in an unrecognised format.
///
/// Handles two on-disk formats:
///   - `name.excalidraw`    — the whole file is a raw JSON object
///   - `name.excalidraw.md` — JSON is inside a ` ```json … ``` ` block
/// Falls back to the `.md` variant automatically when the plain path isn't found.
fn read_excalidraw_json(file_path: &Path) -> Result<String, String> {
    let md_path;
    let paths: &[&Path] = if file_path.to_str().map_or(false, |s| s.ends_with(".md")) {
        &[file_path]
    } else {
        md_path = PathBuf::from(format!("{}.md", file_path.display()));
        &[file_path, md_path.as_path()]
    };

    for &path in paths {
        if let Ok(content) = std::fs::read_to_string(path) {
            if path.to_str().map_or(false, |s| s.ends_with(".excalidraw.md")) {
                let embedded = parse_embedded_files(&content);
                return extract_json_from_excalidraw_md(&content)
                    .map(|json| inject_embedded_files(&json, path, &embedded))
                    .ok_or_else(|| {
                    if content.contains("```compressed-json") {
                        "Excalidraw file uses compressed format. \
                         Open it in Obsidian and run \
                         \"Decompress current Excalidraw file\" from the command palette, \
                         then rebuild the book."
                            .to_string()
                    } else {
                        format!(
                            "No ```json block found in {}. \
                             The file may use an unsupported Excalidraw format.",
                            path.display()
                        )
                    }
                });
            } else {
                return Ok(content);
            }
        }
    }
    Err(format!("Excalidraw file not found: {}", file_path.display()))
}

/// Extract the raw JSON object from an `.excalidraw.md` file.
///
/// Supports two formats produced by the Obsidian Excalidraw plugin:
///   - Uncompressed: scene JSON inside a ` ```json ` fenced block
///   - Compressed:   LZ-string (compressToBase64) data inside a ` ```compressed-json ` block
fn extract_json_from_excalidraw_md(content: &str) -> Option<String> {
    // Uncompressed path — plain JSON block.
    if let Some(json) = extract_fenced_block(content, "```json\n") {
        return Some(json);
    }
    // Compressed path — LZ-string base64 encoded.
    if let Some(compressed) = extract_fenced_block(content, "```compressed-json\n") {
        let u16s = lz_str::decompress_from_base64(&compressed)?;
        return String::from_utf16(&u16s).ok();
    }
    None
}

fn extract_fenced_block(content: &str, marker: &str) -> Option<String> {
    let start = content.find(marker)? + marker.len();
    let rest = &content[start..];
    let end = rest.find("\n```")?;
    Some(rest[..end].to_string())
}

// ---------------------------------------------------------------------------
// Excalidraw pass (pass 2)
// ---------------------------------------------------------------------------

fn process_excalidraw(
    link_re: &Regex,
    wiki_re: &Regex,
    content: &str,
    chapter_dir: &Path,
    depth: usize,
    verbose: bool,
    refs: &mut Vec<ExcalidrawRef>,
) -> String {
    let trailing_newline = content.ends_with('\n');
    let mut result = String::with_capacity(content.len());
    let mut in_code_block = false;
    let mut fence: Option<(char, usize)> = None;

    for (i, line) in content.split('\n').enumerate() {
        if i > 0 {
            result.push('\n');
        }
        let trimmed = line.trim_start();
        let (is_fence, fc, flen) = detect_fence(trimmed);

        if is_fence {
            if !in_code_block {
                in_code_block = true;
                fence = Some((fc, flen));
                result.push_str(line);
            } else if let Some((f, c)) = fence {
                if fc == f && flen >= c {
                    in_code_block = false;
                    fence = None;
                }
                result.push_str(line);
            } else {
                result.push_str(line);
            }
        } else if in_code_block {
            result.push_str(line);
        } else {
            // Wikilinks first, then regular markdown links.
            let line = replace_excalidraw_wikilinks(wiki_re, line, chapter_dir, depth, verbose, refs);
            let line = replace_excalidraw_links(link_re, &line, chapter_dir, depth, verbose, refs);
            result.push_str(&line);
        }
    }

    if trailing_newline && !result.ends_with('\n') {
        result.push('\n');
    }
    result
}

/// Replace `![[file.excalidraw]]` and `[[file.excalidraw|alias]]` wikilinks.
fn replace_excalidraw_wikilinks(
    wiki_re: &Regex,
    text: &str,
    chapter_dir: &Path,
    depth: usize,
    verbose: bool,
    refs: &mut Vec<ExcalidrawRef>,
) -> String {
    wiki_re
        .replace_all(text, |caps: &regex::Captures| {
            let raw_path = &caps[2]; // e.g. "My Drawing.excalidraw"
            let alias = caps.get(3).map(|m| m.as_str()); // optional |alias text

            let decoded = urlencoding::decode(raw_path)
                .unwrap_or(std::borrow::Cow::Borrowed(raw_path));
            let path = Path::new(decoded.as_ref());
            // Wikilinks always end in .excalidraw, so file_stem strips it correctly.
            let stem = path.file_stem().and_then(|s| s.to_str()).unwrap_or("drawing");
            let slug = excalidraw_slug(stem);
            let display = alias.unwrap_or(stem).to_string();
            let href = excalidraw_href(&slug, depth);

            // The file on disk may be name.excalidraw or name.excalidraw.md — try both.
            let base = chapter_dir.join(decoded.as_ref());
            let file_path = if base.exists() {
                base.clone()
            } else {
                PathBuf::from(format!("{}.md", base.display()))
            };

            if verbose {
                eprintln!("[mdbook-obsidian] excalidraw wikilink: {raw_path}  =>  {href}");
            }
            refs.push(ExcalidrawRef { file_path, slug, name: stem.to_string() });
            format!("[{}]({})", display, href)
        })
        .into_owned()
}

/// Replace `[text](file.excalidraw)` and `[text](file.excalidraw.md)` markdown links.
fn replace_excalidraw_links(
    link_re: &Regex,
    text: &str,
    chapter_dir: &Path,
    depth: usize,
    verbose: bool,
    refs: &mut Vec<ExcalidrawRef>,
) -> String {
    link_re
        .replace_all(text, |caps: &regex::Captures| {
            let bang = &caps[1];
            let link_text = &caps[2];
            let raw_path = &caps[3];

            let decoded = urlencoding::decode(raw_path)
                .unwrap_or(std::borrow::Cow::Borrowed(raw_path));
            let path = Path::new(decoded.as_ref());

            // file_stem strips the last extension only:
            //   name.excalidraw     → stem = "name"
            //   name.excalidraw.md  → stem = "name.excalidraw" — strip again
            let stem_raw = path.file_stem().and_then(|s| s.to_str()).unwrap_or("drawing");
            let stem = stem_raw.strip_suffix(".excalidraw").unwrap_or(stem_raw);

            let slug = excalidraw_slug(stem);
            let href = excalidraw_href(&slug, depth);
            let file_path = chapter_dir.join(decoded.as_ref());

            if verbose {
                eprintln!("[mdbook-obsidian] excalidraw link: {raw_path}  =>  {href}");
            }
            refs.push(ExcalidrawRef { file_path, slug, name: stem.to_string() });

            let _ = bang; // image-style embed treated identically — becomes a link
            format!("[{}]({})", link_text, href)
        })
        .into_owned()
}

// ---------------------------------------------------------------------------
// Hard line break patching
// ---------------------------------------------------------------------------

/// Convert Obsidian-style single line breaks to CommonMark hard line breaks.
///
/// A single newline between two non-empty lines gets two trailing spaces appended
/// to the first line, which CommonMark treats as a hard break (`<br>`).
/// Lines already ending with `  ` or `\` are left untouched.
/// Content inside fenced code blocks is skipped.
fn patch_hard_line_breaks(content: &str) -> String {
    let mut result = String::with_capacity(content.len() + 64);
    let mut in_code_block = false;
    let mut fence: Option<(char, usize)> = None;
    let lines: Vec<&str> = content.split('\n').collect();

    for (i, &line) in lines.iter().enumerate() {
        if i > 0 {
            result.push('\n');
        }

        let trimmed = line.trim_start();
        let (is_fence, fc, flen) = detect_fence(trimmed);

        if is_fence {
            if !in_code_block {
                in_code_block = true;
                fence = Some((fc, flen));
            } else if let Some((f, c)) = fence {
                if fc == f && flen >= c {
                    in_code_block = false;
                    fence = None;
                }
            }
            result.push_str(line);
            continue;
        }

        if in_code_block {
            result.push_str(line);
            continue;
        }

        let next_nonempty = lines[i + 1..].iter().copied().find(|l| !l.trim().is_empty());
        let needs_break = !line.trim().is_empty()
            && next_nonempty.is_some()
            // next line is adjacent (not separated by a blank line)
            && lines.get(i + 1).map(|l| !l.trim().is_empty()).unwrap_or(false)
            && !line.ends_with("  ")
            && !line.ends_with('\\');

        result.push_str(line);
        if needs_break {
            result.push_str("  ");
        }
    }

    result
}

// ---------------------------------------------------------------------------
// Anchor-normalisation pass (pass 1) — unchanged from before
// ---------------------------------------------------------------------------

fn process_content(re: &Regex, content: &str, verbose: bool) -> String {
    let trailing_newline = content.ends_with('\n');
    let mut result = String::with_capacity(content.len());
    let mut in_code_block = false;
    let mut fence: Option<(char, usize)> = None;

    for (i, line) in content.split('\n').enumerate() {
        if i > 0 {
            result.push('\n');
        }
        let trimmed = line.trim_start();
        let (is_fence, fc, flen) = detect_fence(trimmed);

        if is_fence {
            if !in_code_block {
                in_code_block = true;
                fence = Some((fc, flen));
                result.push_str(line);
            } else if let Some((f, c)) = fence {
                if fc == f && flen >= c {
                    in_code_block = false;
                    fence = None;
                }
                result.push_str(line);
            } else {
                result.push_str(line);
            }
        } else if in_code_block {
            result.push_str(line);
        } else {
            result.push_str(&transform_line(re, line, verbose));
        }
    }

    if trailing_newline && !result.ends_with('\n') {
        result.push('\n');
    }
    result
}

fn detect_fence(trimmed: &str) -> (bool, char, usize) {
    for &fc in &['`', '~'] {
        if trimmed.starts_with(fc) {
            let n = trimmed.chars().take_while(|&c| c == fc).count();
            if n >= 3 {
                return (true, fc, n);
            }
        }
    }
    (false, '`', 0)
}

fn transform_line(re: &Regex, line: &str, verbose: bool) -> String {
    let mut result = String::new();
    let mut remaining = line;

    while !remaining.is_empty() {
        match remaining.find('`') {
            None => {
                result.push_str(&replace_links(re, remaining, verbose));
                break;
            }
            Some(pos) => {
                result.push_str(&replace_links(re, &remaining[..pos], verbose));
                remaining = &remaining[pos..];

                let tick_count = remaining.chars().take_while(|&c| c == '`').count();
                let after_open = &remaining[tick_count..];
                let closing = "`".repeat(tick_count);

                match after_open.find(closing.as_str()) {
                    Some(end) => {
                        let span_end = tick_count + end + tick_count;
                        result.push_str(&remaining[..span_end]);
                        remaining = &remaining[span_end..];
                    }
                    None => {
                        result.push_str(&replace_links(re, remaining, verbose));
                        break;
                    }
                }
            }
        }
    }

    result
}

fn replace_links(re: &Regex, text: &str, verbose: bool) -> String {
    re.replace_all(text, |caps: &regex::Captures| {
        let bang = &caps[1];
        let link_text = &caps[2];
        let url = &caps[3];

        if bang == "!" {
            return format!("![{}]({})", link_text, url);
        }

        let new_url = normalize_link(url);
        if verbose && new_url != url[..] {
            eprintln!("[mdbook-obsidian] link: {url}  =>  {new_url}");
        }
        format!("[{}]({})", link_text, new_url)
    })
    .into_owned()
}

fn normalize_link(url: &str) -> String {
    if url.starts_with("http://")
        || url.starts_with("https://")
        || url.starts_with("//")
        || url.starts_with("mailto:")
    {
        return url.to_owned();
    }

    if url.starts_with('#') {
        return format!("#{}", normalize_fragment(&url[1..]));
    }

    match url.find('#') {
        None => url.to_owned(),
        Some(i) => format!("{}#{}", &url[..i], normalize_fragment(&url[i + 1..])),
    }
}

fn normalize_fragment(fragment: &str) -> String {
    let decoded = urlencoding::decode(fragment).unwrap_or(std::borrow::Cow::Borrowed(fragment));
    decoded.to_lowercase().replace(' ', "-")
}

// ---------------------------------------------------------------------------
// Binary entry point
// ---------------------------------------------------------------------------

fn main() {
    eprintln!(
        "[mdbook-obsidian] invoked with args: {:?}",
        std::env::args().collect::<Vec<_>>()
    );
    let preprocessor = ObsidianPreprocessor;
    let args: Vec<String> = std::env::args().collect();

    if args.len() > 1 && args[1] == "supports" {
        let renderer = args.get(2).map(String::as_str).unwrap_or("");
        match preprocessor.supports_renderer(renderer) {
            Ok(true) => process::exit(0),
            _ => process::exit(1),
        }
    }

    let (ctx, book) =
        parse_input(io::stdin()).expect("failed to parse mdbook preprocessor input");
    let result = preprocessor.run(&ctx, book).expect("preprocessor failed");
    serde_json::to_writer(io::stdout(), &result).expect("failed to write output");
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    fn link_re() -> Regex {
        Regex::new(r"(!?)\[([^\]]*)\]\(([^)]+)\)").unwrap()
    }

    // --- image links: never transformed ---

    #[test]
    fn skips_image_links_with_encoded_path() {
        let input = "![alt](Pasted%20Image%2020250424.png)";
        assert_eq!(replace_links(&link_re(), input, false), input);
    }

    #[test]
    fn skips_image_links_with_subdir() {
        let input = "![screenshot](attachments/Pasted%20Image.png)";
        assert_eq!(replace_links(&link_re(), input, false), input);
    }

    // --- same-page anchor normalization ---

    #[test]
    fn normalizes_same_page_anchor_with_encoding() {
        let input = "[Grade 1](#Grade%201%20-%20Color)";
        assert_eq!(
            replace_links(&link_re(), input, false),
            "[Grade 1](#grade-1---color)"
        );
    }

    #[test]
    fn already_normalized_same_page_anchor_unchanged() {
        assert_eq!(
            replace_links(&link_re(), "[top](#top)", false),
            "[top](#top)"
        );
    }

    #[test]
    fn file_path_left_unchanged() {
        let input = "[Link](A%20file-name%20with%20space.md)";
        assert_eq!(replace_links(&link_re(), input, false), input);
    }

    #[test]
    fn normalizes_anchor_in_cross_page_link() {
        let input = "[Link](My%20Note.md#Grade%201%20-%20Color)";
        assert_eq!(
            replace_links(&link_re(), input, false),
            "[Link](My%20Note.md#grade-1---color)"
        );
    }

    #[test]
    fn skips_external_urls() {
        let input = "[Rust](https://www.rust-lang.org)";
        assert_eq!(replace_links(&link_re(), input, false), input);
    }

    // --- code block / inline code skipping ---

    #[test]
    fn skips_fenced_code_blocks() {
        let input = "```\n[Link](#Grade%201)\n```";
        assert_eq!(process_content(&link_re(), input, false), input);
    }

    #[test]
    fn skips_inline_code() {
        let input = "text `[Link](#Grade%201)` end";
        assert_eq!(transform_line(&link_re(), input, false), input);
    }

    #[test]
    fn transforms_outside_inline_code() {
        let input = "[A](#Grade%201) and `code` and [B](#Math%20Class)";
        assert_eq!(
            transform_line(&link_re(), input, false),
            "[A](#grade-1) and `code` and [B](#math-class)"
        );
    }

    // --- excalidraw slug ---

    #[test]
    fn slug_lowercases_and_hyphenates() {
        assert_eq!(excalidraw_slug("My Drawing"), "my-drawing");
    }

    #[test]
    fn slug_strips_non_alphanumeric() {
        assert_eq!(excalidraw_slug("plan (v2)"), "plan-v2");
    }

    // --- excalidraw wikilink replacement ---

    fn wiki_re() -> Regex {
        Regex::new(r"(!?)\[\[([^\]]+\.excalidraw)(?:\|([^\]]*))?\]\]").unwrap()
    }

    fn excalidraw_link_re() -> Regex {
        Regex::new(r"(!?)\[([^\]]*)\]\(([^)]*\.excalidraw(?:\.md)?)\)").unwrap()
    }

    #[test]
    fn replaces_excalidraw_wikilink() {
        let mut refs = vec![];
        let got = replace_excalidraw_wikilinks(
            &wiki_re(),
            "![[My Drawing.excalidraw]]",
            Path::new("/src"),
            0,
            false,
            &mut refs,
        );
        assert_eq!(got, "[My Drawing](_excalidraw/my-drawing.html)");
        assert_eq!(refs.len(), 1);
        assert_eq!(refs[0].slug, "my-drawing");
    }

    #[test]
    fn respects_wikilink_alias() {
        let mut refs = vec![];
        let got = replace_excalidraw_wikilinks(
            &wiki_re(),
            "[[plan.excalidraw|See the plan]]",
            Path::new("/src"),
            0,
            false,
            &mut refs,
        );
        assert_eq!(got, "[See the plan](_excalidraw/plan.html)");
    }

    #[test]
    fn adjusts_href_depth() {
        let mut refs = vec![];
        let got = replace_excalidraw_wikilinks(
            &wiki_re(),
            "![[draw.excalidraw]]",
            Path::new("/src/a/b"),
            2,
            false,
            &mut refs,
        );
        assert_eq!(got, "[draw](../../_excalidraw/draw.html)");
    }

    #[test]
    fn replaces_excalidraw_markdown_link() {
        let mut refs = vec![];
        let got = replace_excalidraw_links(
            &excalidraw_link_re(),
            "[diagram](my-diagram.excalidraw)",
            Path::new("/src"),
            0,
            false,
            &mut refs,
        );
        assert_eq!(got, "[diagram](_excalidraw/my-diagram.html)");
        assert_eq!(refs[0].slug, "my-diagram");
    }

    #[test]
    fn replaces_excalidraw_md_link() {
        // .excalidraw.md format — the link mdBook would have rendered as .excalidraw.html
        let mut refs = vec![];
        let got = replace_excalidraw_links(
            &excalidraw_link_re(),
            "[Castle word puzzle.excalidraw](../Castle%20word%20puzzle.excalidraw.md)",
            Path::new("/src/a/b"),
            2,
            false,
            &mut refs,
        );
        assert_eq!(got, "[Castle word puzzle.excalidraw](../../_excalidraw/castle-word-puzzle.html)");
        assert_eq!(refs[0].slug, "castle-word-puzzle");
        assert_eq!(refs[0].name, "Castle word puzzle");
    }

    #[test]
    fn extracts_json_from_excalidraw_md() {
        let content = "---\nexcalidraw-plugin: parsed\n---\n\n%%\n# Drawing\n```json\n{\"type\":\"excalidraw\"}\n```\n%%\n";
        let json = extract_json_from_excalidraw_md(content).unwrap();
        assert_eq!(json, r#"{"type":"excalidraw"}"#);
    }

    #[test]
    fn decompresses_compressed_json_from_excalidraw_md() {
        let json = r#"{"type":"excalidraw","version":2,"elements":[]}"#;
        // Compress using the same algorithm the Obsidian plugin uses (LZ-string compressToBase64).
        let utf16: Vec<u16> = json.encode_utf16().collect();
        let compressed_str = lz_str::compress_to_base64(&utf16);
        let content = format!(
            "---\nexcalidraw-plugin: parsed\n---\n\n# Drawing\n```compressed-json\n{compressed_str}\n```\n"
        );
        let result = extract_json_from_excalidraw_md(&content).unwrap();
        assert_eq!(result, json);
    }

    #[test]
    fn json_escaping_prevents_script_injection() {
        let r = ExcalidrawRef {
            file_path: PathBuf::from("/fake.excalidraw"),
            slug: "test".into(),
            name: "test".into(),
        };
        let json = r#"{"text":"</script><script>alert(1)</script>"}"#;
        let chapter = make_excalidraw_chapter(&r, json);
        assert!(!chapter.content.contains("</script><script>"));
    }

    // --- hard line break patching ---

    #[test]
    fn hard_break_added_between_adjacent_lines() {
        let input = "line one\nline two\n";
        assert_eq!(patch_hard_line_breaks(input), "line one  \nline two\n");
    }

    #[test]
    fn hard_break_not_added_across_blank_line() {
        let input = "paragraph one\n\nparagraph two\n";
        assert_eq!(patch_hard_line_breaks(input), input);
    }

    #[test]
    fn hard_break_skips_existing_trailing_spaces() {
        let input = "already hard  \nnext\n";
        assert_eq!(patch_hard_line_breaks(input), input);
    }

    #[test]
    fn hard_break_skips_code_block_contents() {
        let input = "text\n```\nline a\nline b\n```\nafter\n";
        assert_eq!(patch_hard_line_breaks(input), "text  \n```\nline a\nline b\n```\nafter\n");
    }
}
